services:
  db:
    image: postgres:15
    container_name: energy_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  deploy:
    build: 
      context: .
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ./deploy:/app
      - ./src:/app/src
      - ./.streamlit:/app/.streamlit
    container_name: energy_streamlit
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}

  analytics:
    build:
      context: .                          # Look at the whole root folder
      dockerfile: ./analytics/Dockerfile  # But read these specific instructions
    volumes:
      - ./analytics:/app
      - ./src:/app/src
      - ./.streamlit:/app/.streamlit
      - ./syles:/app/styles

    container_name: energy_jupyter
    depends_on:
      - db
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}

volumes:
  postgres_data: