services:
  # 1. The Managed PostgreSQL Database
  - type: database
    name: energy_db
    databaseName: energy_forecast
    user: postgres
    plan: free # Use the free tier for testing

  # 2. The Streamlit App
  - type: web
    name: energy_dashboard
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: energy_db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: energy_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: energy_db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: energy_db
          property: password