# 1. Define the Database in its own section
databases:
  - name: energy_db
    databaseName: energy_forecast
    plan: free 

# 2. Define the Services (Worker and Web)
services:
  # Ingest Service
  - type: worker
    name: data_ingestor
    env: python
    buildCommand: pip install -r deploy/requirements.txt
    startCommand: python deploy/app.py
    envVars:
      - key: PYTHONPATH
        value: "."  # <--- THIS IS THE MAGIC LINE
      - key: DB_HOST
        fromDatabase:
          name: energy_db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: energy_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: energy_db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: energy_db
          property: password
      - key: DB_PORT
        value: "5432" # Internal Docker/Render port

  # Streamlit App
  - type: web
    name: energy_dashboard
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: energy_db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: energy_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: energy_db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: energy_db
          property: password
      - key: DB_PORT
        value: "5432"